import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { language } from "@/types";
import Nav from "./components/Nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Multi languagr Blogs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { lang: language };
}>) {
  return (
    <html lang={params.lang}>
      <body className={inter.className}>
        <Nav />
        {children}
      </body>
    </html>
  );
}
